// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent/": {
            "get": {
                "description": "get GetallAgentEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "Get all agent",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.GetAccount"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "create new agent by request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "handler func Create agent endpoinrt",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.accountCreated"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/agent/:agent_id": {
            "get": {
                "description": "get GetOneAgentEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "Get one agent",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.GetAccount"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "edit EditAgentEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "Edit agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agent_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body for editing an agent",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetAccount"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete DeleteAgentEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Agent"
                ],
                "summary": "Delete agent",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/permission/": {
            "get": {
                "description": "get GetallPermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Get all permission",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Permission"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "post CreatePermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Create permission",
                "parameters": [
                    {
                        "description": "Request body for created role",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/permission/{permission_id}": {
            "get": {
                "description": "get GetPermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Get  one permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pemission ID",
                        "name": "permission_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "put EditPermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Edit permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pemission ID",
                        "name": "permission_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body for created role",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete DeletePermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permission"
                ],
                "summary": "Delete permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pemission ID",
                        "name": "permission_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role/": {
            "get": {
                "description": "get GetallRoleEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get all role",
                "responses": {
                    "200": {
                        "description": "role data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Role"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "create  new role by request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "handler func  Create role endpoint",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.roleCreated"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role/:role_id": {
            "get": {
                "description": "put GetoneRoleEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Get one role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.Role"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role/role_permission/": {
            "post": {
                "description": "post CreateRolePermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RolePermission"
                ],
                "summary": "Create role permission",
                "parameters": [
                    {
                        "description": "Request body for created role",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RolePermissionBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role/{role_id}": {
            "put": {
                "description": "put EditRolePermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Role"
                ],
                "summary": "Edit permission role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body for editing an role permission",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PermissionJson"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role/{role_id}/permission_detail": {
            "put": {
                "description": "put UpdateRolePermissionEndpoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RolePermission"
                ],
                "summary": "Update role permission detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "role_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body for editing an role permission",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RolePermissionBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role_permission": {
            "get": {
                "description": "get GetallRolePermissionEndPoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RolePermission"
                ],
                "summary": "Get all role permission",
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.RolePermissionBody"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/role_permission/{role_permiassion_id}": {
            "get": {
                "description": "get GetRolePermissionEndPoint",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RolePermission"
                ],
                "summary": "Get one role permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "role_permiassion_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data",
                        "schema": {
                            "$ref": "#/definitions/models.RolePermissionBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Data not found error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.accountCreated": {
            "type": "object",
            "properties": {
                "auth_type": {
                    "type": "string"
                },
                "azure_ad_id": {
                    "type": "string"
                },
                "confirm_password": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "otp_code": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.roleCreated": {
            "type": "object",
            "properties": {
                "role_name": {
                    "type": "string"
                },
                "role_ref": {
                    "type": "string"
                }
            }
        },
        "models.GetAccount": {
            "type": "object",
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.GroupRolePermission": {
            "type": "object",
            "properties": {
                "model": {
                    "type": "string"
                },
                "permission_id": {
                    "type": "string"
                },
                "permission_name": {
                    "type": "string"
                },
                "permissions": {
                    "$ref": "#/definitions/models.PermissionJson"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Timestamp when the permission was created",
                    "type": "string"
                },
                "module": {
                    "description": "Module or feature associated with the permission",
                    "type": "string"
                },
                "permission_id": {
                    "description": "Unique ID for the permission (Primary Key)",
                    "type": "string"
                },
                "permission_name": {
                    "description": "Name of the permission",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Timestamp when the permission was last updated (Nullable)",
                    "type": "string"
                }
            }
        },
        "models.PermissionJson": {
            "type": "object",
            "properties": {
                "create": {
                    "type": "boolean"
                },
                "delete": {
                    "type": "boolean"
                },
                "edit": {
                    "type": "boolean"
                },
                "view": {
                    "type": "boolean"
                }
            }
        },
        "models.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "วันที่และเวลาที่สร้างบทบาท",
                    "type": "string"
                },
                "permissions": {
                    "description": "สิทธิ์ที่อนุญาตในบทบาทนั้น (JSON)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.PermissionJson"
                        }
                    ]
                },
                "role_id": {
                    "description": "รหัสบทบาท (Primary Key)",
                    "type": "string"
                },
                "role_name": {
                    "description": "ชื่อบทบาท (Unique Index)",
                    "type": "string"
                },
                "updated_at": {
                    "description": "วันที่และเวลาที่อัปเดตบทบาท (Nullable)",
                    "type": "string"
                }
            }
        },
        "models.RolePermissionBody": {
            "type": "object",
            "properties": {
                "group_permission": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GroupRolePermission"
                    }
                },
                "role_id": {
                    "type": "string"
                },
                "role_name": {
                    "type": "string"
                },
                "role_permission_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.9",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Land Registeation API Documentation",
	Description:      "เอกสารการใช้งาน API Land Registeation สำหรับ Developer",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
